# General
title:          pop.pe
description:    glenn online
url:            https://pop.pe
baseurl:        ""

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed
  sourcemap: never

# Contact
author:
  name: glenn poppe
  contacts:
    - name: Bluesky
      url: https://bsky.app/profile/pop.pe
      handle: pop.pe
    - name: LinkedIn
      url: https://www.linkedin.com/in/glennpoppe
      handle: Glenn Poppe
    - name: Signal
      url: https://signal.me/#eu/Ap5OFNrfR6BL-0vbws77Fk7BziNnPAfVdVNH-9jUfYP9D3gsGbpHmrnb4AOgrd4U
      handle: popp.01

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

exclude:
  - new_post.sh
